# Generated by Django 6.0.1 on 2026-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
