# Generated by Django 6.0.1 on 2026-05-09 17:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_departmental_defaults(apps, schema_editor):
    AcademicSession = apps.get_model('portal', 'AcademicSession')
    DepartmentalAssociation = apps.get_model('portal', 'DepartmentalAssociation')
    DepartmentalFee = apps.get_model('portal', 'DepartmentalFee')

    constants = [
        ('departmental_fee', 'Departmental Fee'),
        ('acf', 'ACF'),
        ('mssn', 'MSSN'),
    ]
    associations = []
    for code, name in constants:
        association, _ = DepartmentalAssociation.objects.get_or_create(
            code=code,
            defaults={'name': name, 'is_constant': True},
        )
        associations.append(association)

    session, _ = AcademicSession.objects.get_or_create(
        name='2026/2027',
        defaults={'is_current': True},
    )
    if not session.is_current:
        session.is_current = True
        session.save(update_fields=['is_current'])

    for association in associations:
        DepartmentalFee.objects.get_or_create(
            session=session,
            association=association,
            defaults={'amount': Decimal('0.00')},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_coursepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_current', '-name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('is_constant', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('association_summary', models.CharField(blank=True, max_length=255)),
                ('paystack_reference', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('paystack_public_key_used', models.CharField(blank=True, max_length=255)),
                ('paystack_secret_key_used', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmental_payments', to='portal.department')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.academicsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='departmental_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('white_form', 'White Form'), ('school_receipt', 'School Receipt'), ('supporting', 'Supporting Document')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='departmental/%Y/%m/')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.departmentalpayment')),
            ],
            options={
                'ordering': ['category', 'title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='portal.departmentalassociation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.departmentalpayment')),
            ],
            options={
                'ordering': ['association__created_at', 'association__name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paystack_public_key', models.CharField(blank=True, max_length=255)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=255)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway', to='portal.department')),
            ],
            options={
                'ordering': ['department__name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_fees', to='portal.departmentalassociation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmental_fees', to='portal.academicsession')),
            ],
            options={
                'ordering': ['session__name', 'association__created_at', 'association__name'],
                'constraints': [models.UniqueConstraint(fields=('session', 'association'), name='unique_session_association_fee')],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentalpayment',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_departmental_session_payment'),
        ),
        migrations.AddConstraint(
            model_name='departmentalpaymentitem',
            constraint=models.UniqueConstraint(fields=('payment', 'association'), name='unique_departmental_payment_item'),
        ),
        migrations.RunPython(seed_departmental_defaults, migrations.RunPython.noop),
    ]
