# Generated by Django 6.0.1 on 2026-05-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_academicsession_departmentalassociation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentalfee',
            options={'ordering': ['department__name', 'session__name', 'association__created_at', 'association__name']},
        ),
        migrations.RemoveConstraint(
            model_name='departmentalfee',
            name='unique_session_association_fee',
        ),
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, upload_to='courses/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='departmentalfee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmental_fees', to='portal.department'),
        ),
        migrations.AddConstraint(
            model_name='departmentalfee',
            constraint=models.UniqueConstraint(fields=('session', 'department', 'association'), name='unique_session_department_association_fee'),
        ),
    ]
