# Generated by Django 6.0.1 on 2026-05-24 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_coursepaymentgateway_and_coursepayment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReminderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('alert', 'Alert')], max_length=20)),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('message', 'Message'), ('class_reminder', 'Class Reminder')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('browser_delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursepaymentgateway',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='departmentpaymentgateway',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='browser_alerts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='class_reminder_alerts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_class_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['student', 'is_deleted', 'is_read'], name='portal_noti_student_a27e04_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourseregistration',
            index=models.Index(fields=['student', 'course'], name='portal_stud_student_dc1678_idx'),
        ),
        migrations.AddField(
            model_name='coursereminderdispatch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_dispatches', to='portal.course'),
        ),
        migrations.AddField(
            model_name='coursereminderdispatch',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reminder_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useralert',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coursereminderdispatch',
            index=models.Index(fields=['scheduled_for', 'channel'], name='portal_cour_schedul_434cd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereminderdispatch',
            constraint=models.UniqueConstraint(fields=('course', 'recipient', 'scheduled_for', 'channel'), name='unique_course_reminder_dispatch'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['recipient', 'browser_delivered_at', 'is_read'], name='portal_user_recipie_dab765_idx'),
        ),
        migrations.AddConstraint(
            model_name='useralert',
            constraint=models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='unique_user_alert_dedupe'),
        ),
    ]
