# Generated by Django 6.0.1 on 2026-08-03

from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_coursereminderdispatch_useralert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passport_photo",
            field=models.FileField(
                blank=True,
                upload_to="passports/%Y/%m/",
                validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
            ),
        ),
    ]
