# Generated by Django 6.0.1 on 2026-08-19 17:00

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_course_payments_to_current_session(apps, schema_editor):
    AcademicSession = apps.get_model("portal", "AcademicSession")
    CoursePayment = apps.get_model("portal", "CoursePayment")
    current_session = AcademicSession.objects.filter(is_current=True).first()
    if current_session is None:
        current_session = AcademicSession.objects.order_by("-name").first()
    if current_session is not None:
        CoursePayment.objects.filter(session__isnull=True).update(session=current_session)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_coursereminderdispatch_delivery_tracking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursepayment',
            name='unique_course_payment',
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='portal.academicsession'),
        ),
        migrations.RunPython(assign_existing_course_payments_to_current_session, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='coursepayment',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'session'), name='unique_course_payment'),
        ),
    ]
