# Generated by Django 6.0.1 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_remove_coursepayment_unique_course_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentalpaymentdocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("white_form", "White Form"),
                    ("school_receipt", "School Receipt"),
                    ("supporting", "Medical fitness"),
                    ("additional", "Additional Document"),
                ],
                max_length=20,
            ),
        ),
    ]
