# Generated by Django 6.0.1 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_alter_departmentalpaymentdocument_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentalassociation",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departmental_associations",
                to="portal.department",
            ),
        ),
        migrations.AlterField(
            model_name="departmentalassociation",
            name="code",
            field=models.SlugField(max_length=50),
        ),
        migrations.AlterField(
            model_name="departmentalassociation",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name="departmentalassociation",
            constraint=models.UniqueConstraint(
                fields=("department", "name"),
                name="unique_department_association_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentalassociation",
            constraint=models.UniqueConstraint(
                fields=("department", "code"),
                name="unique_department_association_code",
            ),
        ),
    ]
