# Generated by Django 6.0.1 on 2026-08-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_registrations_to_current_session(apps, schema_editor):
    AcademicSession = apps.get_model("portal", "AcademicSession")
    StudentCourseRegistration = apps.get_model("portal", "StudentCourseRegistration")
    session = AcademicSession.objects.filter(is_current=True).first()
    if session is None:
        session = AcademicSession.objects.order_by("-name").first()
    if session is not None:
        StudentCourseRegistration.objects.filter(session__isnull=True).update(session=session)


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_departmentalassociation_department_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseStudentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("grouping_method", models.CharField(choices=[("department", "By department"), ("random", "Random")], max_length=20)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CourseStudentGroupMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["student__last_name", "student__first_name", "student__username"]},
        ),
        migrations.RemoveConstraint(model_name="coursepayment", name="unique_course_payment"),
        migrations.RemoveConstraint(model_name="studentcourseregistration", name="unique_student_course_registration"),
        migrations.RemoveIndex(model_name="studentcourseregistration", name="portal_stud_student_dc1678_idx"),
        migrations.AddField(model_name="coursepayment", name="enrollment_sequence", field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name="coursepayment", name="is_active_for_registration", field=models.BooleanField(default=True)),
        migrations.AddField(
            model_name="studentcourseregistration",
            name="session",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="student_course_registrations", to="portal.academicsession"),
        ),
        migrations.RunPython(assign_existing_registrations_to_current_session, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="studentcourseregistration",
            index=models.Index(fields=["student", "course", "session"], name="portal_stud_student_b921d9_idx"),
        ),
        migrations.AddConstraint(
            model_name="coursepayment",
            constraint=models.UniqueConstraint(fields=("student", "course", "session", "enrollment_sequence"), name="unique_course_payment"),
        ),
        migrations.AddConstraint(
            model_name="studentcourseregistration",
            constraint=models.UniqueConstraint(fields=("student", "course", "session"), name="unique_student_course_registration"),
        ),
        migrations.AddField(model_name="coursestudentgroup", name="course", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_groups", to="portal.course")),
        migrations.AddField(model_name="coursestudentgroup", name="department", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="course_student_groups", to="portal.department")),
        migrations.AddField(model_name="coursestudentgroup", name="lecturer", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="course_student_groups", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="coursestudentgroup", name="session", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="course_student_groups", to="portal.academicsession")),
        migrations.AddField(model_name="coursestudentgroupmembership", name="group", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="portal.coursestudentgroup")),
        migrations.AddField(model_name="coursestudentgroupmembership", name="student", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="course_group_memberships", to=settings.AUTH_USER_MODEL)),
        migrations.AddConstraint(model_name="coursestudentgroup", constraint=models.UniqueConstraint(fields=("course", "session", "name"), name="unique_course_student_group_name")),
        migrations.AddConstraint(model_name="coursestudentgroupmembership", constraint=models.UniqueConstraint(fields=("group", "student"), name="unique_course_group_member")),
    ]
