# Generated by Django 6.0.1 on 2026-08-31 23:05

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_curricula(apps, schema_editor):
    """Preserve the course version that existing data was already using."""
    AcademicSession = apps.get_model("portal", "AcademicSession")
    Course = apps.get_model("portal", "Course")
    Curriculum = apps.get_model("portal", "Curriculum")
    StudentCourseRegistration = apps.get_model("portal", "StudentCourseRegistration")
    User = apps.get_model("portal", "User")

    current_session = AcademicSession.objects.filter(is_current=True).first()
    curricula = {}

    def curriculum_for(department_id, session_id):
        if not department_id or not session_id:
            return None
        key = (department_id, session_id)
        if key not in curricula:
            curricula[key], _ = Curriculum.objects.get_or_create(
                department_id=department_id,
                effective_session_id=session_id,
            )
        return curricula[key]

    for course in Course.objects.filter(curriculum__isnull=True).iterator():
        session_id = course.academic_session_id or (current_session.id if current_session else None)
        curriculum = curriculum_for(course.department_id, session_id)
        if curriculum:
            Course.objects.filter(pk=course.pk).update(curriculum_id=curriculum.pk)

    for student in User.objects.filter(role="student", curriculum__isnull=True).exclude(department__isnull=True).iterator():
        # A student's earliest stored registration is the best available record
        # of their established programme version.
        registration = (
            StudentCourseRegistration.objects.filter(
                student_id=student.pk,
                course__curriculum__isnull=False,
            )
            .order_by("created_at", "pk")
            .first()
        )
        curriculum_id = registration.course.curriculum_id if registration else None
        if not curriculum_id and current_session:
            curriculum = Curriculum.objects.filter(
                department_id=student.department_id,
                effective_session_id=current_session.id,
            ).first()
            if not curriculum:
                curriculum = Curriculum.objects.filter(
                    department_id=student.department_id,
                    effective_session__name__lte=current_session.name,
                ).order_by("-effective_session__name", "-pk").first()
            curriculum_id = curriculum.pk if curriculum else None
        if curriculum_id:
            User.objects.filter(pk=student.pk).update(curriculum_id=curriculum_id)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_course_academic_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='portal.department')),
                ('effective_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='portal.academicsession')),
            ],
            options={
                'ordering': ['department__name', '-effective_session__name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='portal.curriculum'),
        ),
        migrations.AddField(
            model_name='user',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='The curriculum assigned when this student joined their department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='portal.curriculum'),
        ),
        migrations.RunPython(assign_existing_curricula, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('department', 'effective_session'), name='unique_department_curriculum_session'),
        ),
    ]
