# Generated by Django 6.0.1 on 2026-09-13 07:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def assign_legacy_tenant(apps, schema_editor):
    """Keep all pre-SaaS records together under one compatibility tenant."""
    Institution = apps.get_model("portal", "Institution")
    legacy, _ = Institution.objects.get_or_create(
        institution_code="EDUCONNECT-LEGACY",
        defaults={
            "name": "Educonnect Legacy Institution",
            "institution_type": "other",
            "email": "support@educonnect.local",
            "subdomain": "legacy",
            "status": "active",
        },
    )
    tenant_models = [
        "AcademicSession", "Course", "CourseAllocationUpload", "CourseMaterial",
        "CoursePayment", "CoursePaymentGateway", "CourseReminderDispatch",
        "CourseStudentGroup", "CourseStudentGroupMembership", "Curriculum",
        "Department", "DepartmentalAssociation", "DepartmentalFee",
        "DepartmentalPayment", "DepartmentalPaymentDocument", "DepartmentalPaymentItem",
        "DepartmentCoursePaymentGateway", "DepartmentLecturerUpload",
        "DepartmentPaymentGateway", "Faculty", "Handbook", "InstitutionProfile",
        "LecturerCourseRegistration", "MaterialAccess", "Notification",
        "NotificationAttachment", "NotificationRecipient", "StudentCourseRegistration",
        "Timetable", "UserAlert",
    ]
    for model_name in tenant_models:
        apps.get_model("portal", model_name).objects.filter(institution__isnull=True).update(institution=legacy)
    User = apps.get_model("portal", "User")
    User.objects.filter(institution__isnull=True, is_superuser=False).update(institution=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_curriculum_cohorts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution_code', models.CharField(max_length=32, unique=True)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('college', 'College'), ('other', 'Other')], default='university', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('logo', models.FileField(blank=True, upload_to='institutions/%Y/%m/')),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=253, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('custom_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('max_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('max_storage_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='academicsession',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='courseallocationupload',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='coursepaymentgateway',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='coursereminderdispatch',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='coursestudentgroup',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='coursestudentgroupmembership',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentalassociation',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentalfee',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentalpayment',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentalpaymentdocument',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentalpaymentitem',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentcoursepaymentgateway',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentlecturerupload',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='departmentpaymentgateway',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='lecturercourseregistration',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='materialaccess',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='notification',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='notificationattachment',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='studentcourseregistration',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='portal.institution'),
        ),
        migrations.AddField(
            model_name='useralert',
            name='institution',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expiring_soon', 'Expiring soon'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='portal.institution')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='portal.subscriptionplan')),
            ],
            options={
                'ordering': ['-end_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='portal.institution')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='portal.subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='portal.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='portal.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='portal.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'action', 'created_at'], name='portal_audi_institu_cad6e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiry', models.IntegerField()),
                ('channel', models.CharField(default='email', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portal.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'days_before_expiry', 'channel'), name='unique_subscription_notification')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['institution', 'status', 'end_date'], name='portal_subs_institu_bb2160_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['institution', 'status', 'created_at'], name='portal_paym_institu_f951a2_idx'),
        ),
        migrations.RunPython(assign_legacy_tenant, migrations.RunPython.noop),
    ]
