# Generated by Django 6.0.1 on 2026-09-13 07:50

import django.contrib.auth.models
import portal.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_multi_tenant_saas'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', portal.models.TenantUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
