# Generated by Django 6.0.1 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0024_tenant_scoped_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_trial",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
