# Generated by Django 6.0.1 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0025_subscriptionplan_is_trial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("institution", "id_number"),
                name="unique_institution_user_id_number",
            ),
        ),
        migrations.AlterField(
            model_name="academicsession",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.UniqueConstraint(
                fields=("institution", "name"),
                name="unique_institution_academic_session_name",
            ),
        ),
        migrations.AlterField(
            model_name="coursepaymentgateway",
            name="slug",
            field=models.CharField(default="courses", max_length=30),
        ),
        migrations.AddConstraint(
            model_name="coursepaymentgateway",
            constraint=models.UniqueConstraint(
                fields=("institution", "slug"),
                name="unique_institution_course_gateway_slug",
            ),
        ),
    ]
