# Generated by Django 6.0.1 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


def create_legacy_plan_durations(apps, schema_editor):
    SubscriptionPlan = apps.get_model("portal", "SubscriptionPlan")
    SubscriptionPlanDuration = apps.get_model("portal", "SubscriptionPlanDuration")
    period_days = {"monthly": 30, "quarterly": 90, "yearly": 365}
    for plan in SubscriptionPlan.objects.filter(is_trial=False):
        duration_days = period_days.get(plan.billing_period, plan.custom_duration_days or 0)
        if duration_days in {183, 365, 730, 1825}:
            SubscriptionPlanDuration.objects.get_or_create(
                plan=plan,
                duration_days=duration_days,
                defaults={"price": plan.price, "is_active": plan.is_active},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0026_tenant_scoped_user_sessions_and_gateways"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPaymentGateway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(default="subscription", max_length=30, unique=True)),
                ("paystack_public_key", models.CharField(blank=True, max_length=255)),
                ("paystack_secret_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlanDuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("duration_days", models.PositiveIntegerField(choices=[(183, "6 months"), (365, "1 year"), (730, "2 years"), (1825, "5 years")])),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="durations", to="portal.subscriptionplan")),
            ],
            options={"ordering": ["plan__name", "duration_days"]},
        ),
        migrations.RunPython(create_legacy_plan_durations, migrations.RunPython.noop),
        migrations.AddField(
            model_name="payment",
            name="duration_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplanduration",
            constraint=models.UniqueConstraint(fields=("plan", "duration_days"), name="unique_subscription_plan_duration"),
        ),
    ]
