# Generated by Django 6.0.1 on 2026-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auditlog_old_value_auditlog_new_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='institutionprofile',
            constraint=models.UniqueConstraint(fields=('institution',), name='unique_institution_profile'),
        ),
    ]
