# Generated by Django 6.0.1 on 2026-09-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_institution_profile_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionnotification',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionnotification',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
