# Generated by Django 6.0.1 on 2026-09-20 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_primary_roles(apps, schema_editor):
    """Mirror legacy primary roles into the additive multi-role table."""
    User = apps.get_model('portal', 'User')
    RoleAssignment = apps.get_model('portal', 'RoleAssignment')
    for user in User.objects.exclude(institution__isnull=True).iterator():
        RoleAssignment.objects.get_or_create(
            institution_id=user.institution_id,
            user_id=user.pk,
            role=user.role,
            department_id=user.department_id if user.role in {'lecturer', 'hod'} else None,
            defaults={'is_active': True},
        )


def reverse_preserve_legacy_primary_roles(apps, schema_editor):
    # RoleAssignment is additive; reversing the migration must not alter the
    # pre-existing User.role values.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_repair_missing_user_institution_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('expired', 'Expired'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Institution Admin'), ('student', 'Student'), ('lecturer', 'Lecturer'), ('mis', 'MIS'), ('bursary', 'Bursary'), ('admission_officer', 'Admission Officer'), ('academic_planning', 'Academic Planning'), ('hod', 'HOD'), ('exam_officer', 'Exam Officer'), ('senate_member', 'Senate Member'), ('parent_guardian', 'Parent/Guardian')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='AIAutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='ai_automation/%Y/%m/')),
                ('command', models.TextField()),
                ('action', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('analyzed', 'Analyzed'), ('approved', 'Approved'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='analyzed', max_length=16)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('proposed_changes', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_summary', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_automation_approvals', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_automation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'status', 'created_at'], name='portal_aiau_institu_2c15f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(default='Guardian', max_length=50)),
                ('can_view_results', models.BooleanField(default=True)),
                ('can_view_finance', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarded_students', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institution', 'guardian', 'student'), name='unique_guardian_student_link')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Institution Admin'), ('student', 'Student'), ('lecturer', 'Lecturer'), ('mis', 'MIS'), ('bursary', 'Bursary'), ('admission_officer', 'Admission Officer'), ('academic_planning', 'Academic Planning'), ('hod', 'HOD'), ('exam_officer', 'Exam Officer'), ('senate_member', 'Senate Member'), ('parent_guardian', 'Parent/Guardian')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.department')),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'role', 'is_active'], name='portal_role_institu_0d5013_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'user', 'role', 'department'), name='unique_tenant_user_role')],
            },
        ),
        migrations.RunPython(preserve_legacy_primary_roles, reverse_preserve_legacy_primary_roles),
    ]
