# Generated by Django 6.0.1 on 2026-09-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_institutional_rbac_ai'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='institutionfeature',
            name='unique_institution_feature',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='institutionfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='institutionfeature',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='InstitutionFeature',
        ),
    ]
