# Generated by Django 6.0.1 on 2026-09-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_remove_institutionfeature_unique_institution_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_sessions', to='portal.academicsession')),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('gender_restriction', models.CharField(choices=[('any', 'Any student'), ('female', 'Female'), ('male', 'Male')], default='any', max_length=12)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accommodation_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_applications', to=settings.AUTH_USER_MODEL)),
                ('accommodation_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='portal.accommodationsession')),
                ('preferred_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='portal.hostel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
            ],
            options={
                'ordering': ['room__block__hostel__name', 'room__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodation_allocations', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation', to='portal.accommodationapplication')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='portal.hostelbed')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='portal.hostel')),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
            ],
            options={
                'ordering': ['hostel__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='portal.hostelblock')),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
            ],
            options={
                'ordering': ['block__hostel__name', 'block__name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='hostelbed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='portal.hostelroom'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=30)),
                ('award', models.CharField(blank=True, max_length=80)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='portal.department')),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='accommodationsession',
            constraint=models.UniqueConstraint(fields=('institution', 'academic_session', 'name'), name='unique_institution_accommodation_session'),
        ),
        migrations.AddConstraint(
            model_name='hostel',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_institution_hostel_code'),
        ),
        migrations.AddIndex(
            model_name='accommodationapplication',
            index=models.Index(fields=['institution', 'status', 'created_at'], name='portal_acco_institu_367b7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='accommodationapplication',
            constraint=models.UniqueConstraint(fields=('student', 'accommodation_session'), name='unique_student_accommodation_session_application'),
        ),
        migrations.AddIndex(
            model_name='accommodationallocation',
            index=models.Index(fields=['institution', 'status', 'allocated_at'], name='portal_acco_institu_0f5190_idx'),
        ),
        migrations.AddConstraint(
            model_name='accommodationallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bed',), name='unique_active_bed_allocation'),
        ),
        migrations.AddConstraint(
            model_name='accommodationallocation',
            constraint=models.UniqueConstraint(fields=('student', 'application'), name='unique_allocation_student_application'),
        ),
        migrations.AddConstraint(
            model_name='hostelblock',
            constraint=models.UniqueConstraint(fields=('hostel', 'name'), name='unique_hostel_block_name'),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(fields=('block', 'code'), name='unique_hostel_block_room_code'),
        ),
        migrations.AddConstraint(
            model_name='hostelbed',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='unique_hostel_room_bed_code'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_institution_programme_code'),
        ),
    ]
