# Generated by Django 6.0.1 on 2026-09-22 20:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_accommodationsession_hostel_accommodationapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('credit_units', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('published', 'Published'), ('returned', 'Returned for correction')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='portal.course')),
                ('institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='portal.institution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_reviewed', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_results', to='portal.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_results', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__code', 'student__last_name', 'student__first_name'],
                'indexes': [models.Index(fields=['institution', 'status', 'session'], name='portal_cour_institu_02f079_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'session'), name='unique_student_course_result'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='course_result_score_range')],
            },
        ),
    ]
