# Generated by Django 6.0.1 on 2026-09-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_courseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.programme'),
        ),
    ]
