# Generated by Django 6.0.1 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0037_user_programme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curriculum",
            options={"ordering": ["department__name", "-effective_session__name", "-version"]},
        ),
        migrations.AddField(
            model_name="curriculum",
            name="version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RemoveConstraint(
            model_name="curriculum",
            name="unique_department_curriculum_session",
        ),
        migrations.AddConstraint(
            model_name="curriculum",
            constraint=models.UniqueConstraint(
                fields=("department", "effective_session", "version"),
                name="unique_department_curriculum_session_version",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_department_session_course",
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("department", "code", "curriculum"),
                name="unique_department_curriculum_course",
            ),
        ),
    ]
