from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = "portal"

urlpatterns = [
    path("", views.index, name="home"),
    path("login/", views.portal_login, name="login"),
    path("login/<str:role>/", views.portal_login, name="role-login"),
    path("register/student/", views.student_signup, name="student-signup"),
    path("register/lecturer/", views.lecturer_signup, name="lecturer-signup"),
    path("paystack/webhook/", views.paystack_webhook, name="paystack-webhook"),
    path("logout/", views.portal_logout, name="logout"),
    path("dashboard/", views.dashboard_redirect, name="dashboard"),
    path("profile/", views.profile, name="profile"),
    path("profile/password-reset/", views.send_profile_password_reset, name="profile-password-reset"),
    path("password-reset/", auth_views.PasswordResetView.as_view(
        template_name="portal/password_reset_form.html",
        email_template_name="portal/emails/password_reset_email.txt",
        subject_template_name="portal/emails/password_reset_subject.txt",
        success_url=reverse_lazy("portal:password-reset-done"),
    ), name="password-reset"),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="portal/password_reset_done.html"),
        name="password-reset-done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="portal/password_reset_confirm.html",
            success_url=reverse_lazy("portal:password-reset-complete"),
        ),
        name="password-reset-confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(template_name="portal/password_reset_complete.html"),
        name="password-reset-complete",
    ),
    path("student/", views.student_dashboard, name="student-dashboard"),
    path("student/departmental/", views.student_departmental, name="student-departmental"),
    path("student/departmental/<int:payment_id>/callback/", views.departmental_payment_callback, name="departmental-payment-callback"),
    path("student/courses/", views.student_courses, name="student-courses"),
    path("student/courses/payments/<int:payment_id>/callback/", views.course_payment_callback, name="course-payment-callback"),
    path("student/courses/<int:registration_id>/delete/", views.student_unregister_course, name="student-course-delete"),
    path("student/materials/", views.student_materials, name="student-materials"),
    path("student/messages/", views.student_messages, name="student-messages"),
    path("student/messages/<int:recipient_id>/delete/", views.student_delete_message, name="student-message-delete"),
    path("student/documents/", views.student_documents, name="student-documents"),
    path("lecturer/", views.lecturer_dashboard, name="lecturer-dashboard"),
    path("lecturer/departmental/", views.lecturer_departmental, name="lecturer-departmental"),
    path("lecturer/departmental/download/", views.lecturer_departmental, name="lecturer-departmental-download"),
    path("lecturer/departmental/api-and-document/", views.hod_departmental_apis, name="hod-api-and-document"),
    path("lecturer/departmental/api/", views.hod_departmental_apis, name="hod-departmental-apis"),
    path("lecturer/departmental/fees/", views.hod_departmental_fees, name="hod-departmental-fees"),
    path("lecturer/users/", views.lecturer_students, name="lecturer-users"),
    path("lecturer/courses/", views.lecturer_courses, name="lecturer-courses"),
    path("lecturer/courses/<int:course_id>/paid-students/", views.lecturer_paid_course_student_search, name="lecturer-paid-course-student-search"),
    path("lecturer/courses/<int:course_id>/groups/", views.lecturer_course_groups, name="lecturer-course-groups"),
    path("lecturer/courses/<int:course_id>/paid-students/pdf/", views.lecturer_paid_course_students_pdf, name="lecturer-paid-course-students-pdf"),
    path("lecturer/materials/", views.lecturer_materials, name="lecturer-materials"),
    path("lecturer/materials/<int:material_id>/delete/", views.lecturer_delete_material, name="lecturer-material-delete"),
    path("lecturer/students/", views.lecturer_students, name="lecturer-students"),
    path("lecturer/students/pdf/", views.lecturer_students_pdf, name="lecturer-students-pdf"),
    path("lecturer/material-access/<int:access_id>/<str:status>/", views.lecturer_update_material_access, name="lecturer-material-access"),
    path("lecturer/messages/", views.lecturer_messages, name="lecturer-messages"),
    path("lecturer/messages/<int:notification_id>/delete/", views.lecturer_delete_message, name="lecturer-message-delete"),
    path("lecturer/documents/", views.lecturer_documents, name="lecturer-documents"),
    path("alerts/preferences/", views.update_alert_preferences, name="alert-preferences"),
    path("alerts/feed/", views.alerts_feed, name="alerts-feed"),
    path("admin-portal/", views.admin_dashboard, name="admin-dashboard"),
    path("admin-portal/departmental/", views.admin_departmental, name="admin-departmental"),
    path("admin-portal/departmental/apis/", views.admin_departmental_apis, name="admin-departmental-apis"),
    path("admin-portal/departmental/fees/", views.admin_departmental_fees, name="admin-departmental-fees"),
    path("admin-portal/departmental/download/", views.admin_departmental_download, name="admin-departmental-download"),
    path("admin-portal/departmental/users/", views.admin_departmental_users, name="admin-departmental-users"),
    path("admin-portal/course-api/", views.admin_course_api, name="admin-course-api"),
    path("admin-portal/departments/", views.admin_departments, name="admin-departments"),
    path("admin-portal/hods/", views.admin_hods, name="admin-hods"),
    path("admin-portal/faculties/", views.admin_faculties, name="admin-faculties"),
    path("admin-portal/about/", views.admin_about, name="admin-about"),
    path("admin-portal/courses/", views.admin_courses, name="admin-courses"),
    path("admin-portal/documents/", views.admin_documents, name="admin-documents"),
    path("admin-portal/materials/", views.admin_materials, name="admin-materials"),
    path("admin-portal/users/", views.admin_users, name="admin-users"),
    path("admin-portal/users/<int:user_id>/approve/", views.admin_approve_lecturer, name="admin-approve-lecturer"),
    path("admin-portal/users/<int:user_id>/reset-password/", views.admin_reset_user_password, name="admin-reset-user-password"),
    path("admin-portal/users/<int:user_id>/delete/", views.admin_delete_user, name="admin-delete-user"),
    path("admin-portal/departments/<int:department_id>/delete/", views.admin_delete_department, name="admin-delete-department"),
    path("admin-portal/courses/<int:course_id>/delete/", views.admin_delete_course, name="admin-delete-course"),
    path("admin-portal/materials/<int:material_id>/delete/", views.admin_delete_material, name="admin-delete-material"),
    path("admin-portal/documents/<str:kind>/<int:document_id>/delete/", views.admin_delete_document, name="admin-delete-document"),
    path("departmental/documents/<int:document_id>/download/", views.download_departmental_document, name="download-departmental-document"),
    path("departmental/payments/<int:payment_id>/exam-card/", views.download_exam_card, name="download-exam-card"),
    path("departmental/student-ids/pdf/", views.departmental_student_ids_pdf, name="departmental-student-ids-pdf"),
    path("courses/<int:course_id>/download/", views.download_course_file, name="download-course-file"),
    path("materials/<int:material_id>/download/", views.download_material, name="download-material"),
    path("messages/<int:notification_id>/attachment/", views.download_message_attachment, name="download-message-attachment"),
    path("messages/attachments/<int:attachment_id>/download/", views.download_notification_attachment, name="download-notification-attachment"),
    path("documents/<str:kind>/<int:document_id>/download/", views.download_document, name="download-document"),
]
